name: weather-prediction

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 11 PM UTC (== 3 AM EST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m pytest weather_prediction_test.py

      - name: Lint
        run: |
          pylint weather_prediction.py
          pylint weather_prediction_test.py
        continue-on-error: true

      - name: Execute Python Script for weather prediction
        run: |
          export output=$(python weather_prediction.py)
          echo "Prediction for $output"
          histchars=
          start_delimiter="<!-- start-quote -->"
          end_delimiter="<!-- end-quote -->"
          sed -i "/$start_delimiter/,/$end_delimiter/d" README.md
          printf "$start_delimiter\nPrediction for $output\n$end_delimiter\n" >> README.md
          git diff
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git diff --quiet || (git add README.md && git commit -m "Added new quote to README")
          git push origin main

