name: weather-prediction

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 11 PM UTC (== 3 AM EST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Execute Python Script for weather prediction
        run: python weather_prediction.py
