name: weather-prediction

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 11 PM UTC (== 3 AM EST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
#       - name: Lint
#         run: |
#         	pylint weather_prediction.py
#           pylint weather_prediction_test.py

      - name: Test
        run: |
          python -m pytest weather_prediction_test.py

      - name: Execute Python Script for weather prediction
        run: output=$(python weather_prediction.py)
          echo "::set-output name=pred_weather::$output"
        id: step1

      - name: Print Weather Predictions
        run: echo "${{ steps.step1.outputs.pred_weather }}"
